node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (node:net:1811:16)
    at listenInCluster (node:net:1859:12)
    at Server.listen (node:net:1947:7)
    at Function.listen (/CHECKER/workdir/Checker/node_modules/express/lib/application.js:635:24)
    at Object.<anonymous> (/CHECKER/workdir/Checker/app.js:143:5)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1838:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 5000
}

Node.js v18.19.1
Server is running on http://localhost:5000
Server is running on http://localhost:5000
Server is running on http://localhost:5000
Server is running on http://localhost:5000
Server is running on http://localhost:5000
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: Packets out of order. Got: 0 Expected: 11
    at Parser._tryReadPacketHeader (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Parser.js:470:15)
    at Parser.write (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Parser.js:33:29)
    at Protocol.write (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/CHECKER/workdir/Checker/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/CHECKER/workdir/Checker/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/CHECKER/workdir/Checker/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (node:events:517:28)
    at Protocol._delegateError (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleParserError (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Protocol.js:380:10)
    at Parser._tryReadPacketHeader (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Parser.js:478:10)
    at Parser.write (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Parser.js:33:29)
    [... lines matching original stack trace ...]
    at Socket.emit (node:events:517:28) {
  code: 'PROTOCOL_PACKETS_OUT_OF_ORDER',
  fatal: true
}

Node.js v18.19.1
Server is running on http://localhost:5000
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: Packets out of order. Got: 0 Expected: 11
    at Parser._tryReadPacketHeader (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Parser.js:470:15)
    at Parser.write (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Parser.js:33:29)
    at Protocol.write (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/CHECKER/workdir/Checker/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/CHECKER/workdir/Checker/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/CHECKER/workdir/Checker/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (node:events:517:28)
    at Protocol._delegateError (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleParserError (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Protocol.js:380:10)
    at Parser._tryReadPacketHeader (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Parser.js:478:10)
    at Parser.write (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Parser.js:33:29)
    [... lines matching original stack trace ...]
    at Socket.emit (node:events:517:28) {
  code: 'PROTOCOL_PACKETS_OUT_OF_ORDER',
  fatal: true
}

Node.js v18.19.1
Server is running on http://localhost:5000
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: Packets out of order. Got: 0 Expected: 11
    at Parser._tryReadPacketHeader (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Parser.js:470:15)
    at Parser.write (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Parser.js:33:29)
    at Protocol.write (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/CHECKER/workdir/Checker/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/CHECKER/workdir/Checker/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/CHECKER/workdir/Checker/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (node:events:517:28)
    at Protocol._delegateError (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleParserError (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Protocol.js:380:10)
    at Parser._tryReadPacketHeader (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Parser.js:478:10)
    at Parser.write (/CHECKER/workdir/Checker/node_modules/mysql/lib/protocol/Parser.js:33:29)
    [... lines matching original stack trace ...]
    at Socket.emit (node:events:517:28) {
  code: 'PROTOCOL_PACKETS_OUT_OF_ORDER',
  fatal: true
}

Node.js v18.19.1
